{
 "title": "Terminals scalability",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": "SELECT benchmark_type FROM test_table;"
   }
  ]
 },
 "panels": [
  {
   "title": "$Type scalability ",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for $Type in the time range selected.",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = '$Type'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  git_commit_id\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp'\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Commit ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  git_commit_id\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp'\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "$Type - % Change",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct terminals,\n  (FIRST_VALUE(CAST(result->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE(CAST(result->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE(CAST(result->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\n   \nFROM test_table\nWHERE\n   $__timeFilter(time) AND \n   benchmark_type = '$Type'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last $Type - Worst",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  terminals,\n  result->>'throughput' as \"throughput\"\nFROM test_table\nWHERE\n  id IN (SELECT\n      DISTINCT ON (terminals) id\n    FROM test_table\n    WHERE\n      $__timeFilter(time) AND\n      benchmark_type = '$Type'\n    GROUP BY time, terminals, id\n    ORDER BY terminals, time desc) AND\n  $__timeFilter(time) AND\n  benchmark_type = '$Type'\nORDER BY result->>'throughput' ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Last $Type - Best",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  terminals,\n  result->>'throughput' as \"throughput\"\nFROM test_table\nWHERE\n  id IN (SELECT\n      DISTINCT ON (terminals) id\n    FROM test_table\n    WHERE\n      $__timeFilter(time) AND\n      benchmark_type = '$Type'\n    GROUP BY time, terminals, id\n    ORDER BY terminals, time desc) AND\n  $__timeFilter(time) AND\n  benchmark_type = '$Type'\nORDER BY result->>'throughput' DESC\nLIMIT 1"
    }
   ]
  }
 ]
}